services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  QameraAi\Module\Controller\Admin\:
    resource: '../../src/Controller/Admin'
    tags: ['controller.service_arguments']
