<?php

declare(strict_types=1);

namespace QameraAi\Module\Gallery\Browse;

/**
 * A packshot as shown in the browse accordion. `generatedByJobId` set means
 * the packshot was generated by a job (so it has a backing job output and is
 * importable into the PS gallery); null means it was ingested from a gallery
 * image and therefore originates from the gallery — not importable (D11).
 */
final class BrowsePackshot
{
    public ?Thumbnail $thumbnail = null;

    public function __construct(
        public readonly string $packshotId,
        public readonly ?string $sourceImageId,
        public readonly string $assetId,
        public readonly ?string $generatedByJobId,
    ) {
    }

    public function isGenerated(): bool
    {
        return $this->generatedByJobId !== null;
    }

    public function isImportable(): bool
    {
        // Only job-output-backed (generated) packshots are importable; the
        // origin guard is structural — ingested packshots have no job output.
        return $this->isGenerated();
    }
}
