services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - ps9_mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-pprestashop']
      interval: 5s
      retries: 20

  prestashop:
    image: prestashop/prestashop:9.0-apache
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: prestashop
      DB_PREFIX: ps_
      PS_DOMAIN: localhost:8080
      PS_INSTALL_AUTO: 1
      PS_INSTALL_DB: 1
      PS_LANGUAGE: en
      PS_COUNTRY: pl
      ADMIN_MAIL: admin@example.com
      ADMIN_PASSWD: admin1234
    ports:
      - '8080:80'
    volumes:
      - ../:/var/www/html/modules/qameraai:rw
      - ps9_data:/var/www/html

volumes:
  ps9_mysql:
  ps9_data:
